### PR TITLE
Update dependency specification to JSPM format

### PR DESCRIPTION
**Pull request by TimBailey-pnk**
#11 PR as requested

### CODE REVIEW

**Comment by grofit** [comment]
I will do a publish later on tomorrow for the new version.

**Comment by grofit** [comment]
Hello, so I had some issues trying to build so left it until I had some more time than a few mins here and there to go over it. So currently if I do a build `gulp` it will build after I do a jspm install on the examples but it seems to fail when bundling saying the bundle is not well formed. You seen that happen on your side or do the examples work fine for you?

This isnt to say this problem is related to your changes however currently I cannot build the examples so cannot do a release.

**Comment by grofit** [comment]
As long as I run it through a local server it seems fine now, which is odd as I am sure it used to run perfectly fine from the local system as it had no external cross origin calls. Anyway will get this released now. I have added the carrot to the start of your change though to allow newer versions on the minor.

**Comment by TimBailey-pnk** [comment]
Great thanks.  Let me know if any other weirdness shows up.

**Pull request merged**
